kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: codefresh-local-cluster
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 31243
    hostPort: 8080
    protocol: TCP
    listenAddress: "0.0.0.0"
