global:
  codefresh:
    url: "http://local.codefresh.io" # overridden to be ngrok platform url (see install-gitops-runtime.sh)
    userToken:
      secretKeyRef:
        name: "github-local-dev"
        key: "userToken"
    accountId: "67e27b6f57f583854db5dfe6"
  runtime:
    isConfigurationRuntime: true 
    name: "scotts-local-runtime"
    cluster: https://kubernetes.default.svc
    codefreshHosted: false
    ingressUrl: http://host.docker.internal:8080
    ingress:
      enabled: false
    gitCredentials:
      password:
        secretKeyRef:
          name: "github-local-dev"
          key: "pat"
installer:
  skipValidation: true

tunnel-client:
  enabled: false

internal-router:
  service:
    type: NodePort
    nodePort: 31243

app-proxy:
  config:
    graphqlPlayground: "true"
    cors: "http://local.codefresh.io" # overridden to include ngrok platform url (see install-gitops-runtime.sh)
  # image:
  #   repository: app-proxy
  #   tag: 0.0.1

# gitops-operator:
#   image:
#     repository: quay.io/codefresh/codefresh-gitops-operator
#     tag: v0.3.25
    #cr-26644-b5d5393
